folder_name: 'snmptrapd.v5.7.2'

file_list:
  - file_name: 'glibc-2.17-105.el7.x86_64.rpm'
    url: 'https://buildlogs.centos.org/c7.1511.00/glibc/20151119161215/2.17-105.el7.x86_64/glibc-2.17-105.el7.x86_64.rpm'
  - file_name: 'glibc-common-2.17-105.el7.x86_64.rpm'
    url: 'https://buildlogs.centos.org/c7.1511.00/glibc/20151119161215/2.17-105.el7.x86_64/glibc-common-2.17-105.el7.x86_64.rpm'
  - file_name: 'lm_sensors-libs-3.3.4-11.el7.x86_64.rpm'
    url: 'https://buildlogs.centos.org/c7.01.00/lm_sensors/20150306030219/3.3.4-11.el7.x86_64/lm_sensors-3.3.4-11.el7.x86_64.rpm'
  - file_name: 'net-snmp-5.7.2-24.el7_2.1.x86_64.rpm'
    url: 'https://buildlogs.centos.org/c7.1511.u/net-snmp/20160512103150/5.7.2-24.el7_2.1.x86_64/net-snmp-5.7.2-24.el7_2.1.x86_64.rpm'
  - file_name: 'net-snmp-agent-libs-5.7.2-24.el7_2.1.x86_64.rpm'
    url: 'https://buildlogs.centos.org/c7.1511.u/net-snmp/20160512103150/5.7.2-24.el7_2.1.x86_64/net-snmp-agent-libs-5.7.2-24.el7_2.1.x86_64.rpm'
  - file_name: 'net-snmp-libs-5.7.2-24.el7_2.1.x86_64.rpm'
    url: 'https://buildlogs.centos.org/c7.1511.u/net-snmp/20160512103150/5.7.2-24.el7_2.1.x86_64/net-snmp-libs-5.7.2-24.el7_2.1.x86_64.rpm'
  - file_name: 'openssl098e-0.9.8e-29.el7.centos.3.x86_64.rpm'
    url: 'https://buildlogs.centos.org/c7.1511.u/openssl098e/20160309045539/0.9.8e-29.el7.centos.3.x86_64/openssl098e-0.9.8e-29.el7.centos.3.x86_64.rpm'
  - file_name: 'perl-5.16.3-286.el7.x86_64.rpm'
    url: 'https://buildlogs.centos.org/c7.1511.00/perl/20151120031510/5.16.3-286.el7.x86_64/perl-5.16.3-286.el7.x86_64.rpm'
  - file_name: 'perl-Carp-1.26-244.el7.noarch.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Carp-1.26-244.el7.noarch.rpm'
  - file_name: 'perl-constant-1.27-2.el7.noarch.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-constant-1.27-2.el7.noarch.rpm'
  - file_name: 'perl-Data-Dumper-2.145-3.el7.x86_64.rpm'
    url: 'https://buildlogs.centos.org/c7.00.02/perl-Data-Dumper/20140529192043/2.145-3.el7.x86_64/perl-Data-Dumper-2.145-3.el7.x86_64.rpm'
  - file_name: 'perl-Encode-2.51-7.el7.x86_64.rpm'
    url: 'http://ftp.ksu.edu.tw/FTP/CentOS/7/os/x86_64/Packages/perl-Encode-2.51-7.el7.x86_64.rpm'
  - file_name: 'perl-Exporter-5.68-3.el7.noarch.rpm'
    url: 'https://www.rpmfind.net/linux/centos/7.5.1804/os/x86_64/Packages/perl-Exporter-5.68-3.el7.noarch.rpm'
  - file_name: 'perl-File-Path-2.09-2.el7.noarch.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-File-Path-2.09-2.el7.noarch.rpm'
  - file_name: 'perl-File-Temp-0.23.01-3.el7.noarch.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-File-Temp-0.23.01-3.el7.noarch.rpm'
  - file_name: 'perl-Filter-1.49-3.el7.x86_64.rpm'
    url: 'http://ftp.ksu.edu.tw/FTP/CentOS/7/os/x86_64/Packages/perl-Filter-1.49-3.el7.x86_64.rpm'
  - file_name: 'perl-Getopt-Long-2.40-2.el7.noarch.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Getopt-Long-2.40-3.el7.noarch.rpm'
  - file_name: 'perl-HTTP-Tiny-0.033-3.el7.noarch.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-HTTP-Tiny-0.033-3.el7.noarch.rpm'
  - file_name: 'perl-libs-5.16.3-286.el7.x86_64.rpm'
    url: 'https://buildlogs.centos.org/c7.1511.00/perl/20151120031510/5.16.3-286.el7.x86_64/perl-libs-5.16.3-286.el7.x86_64.rpm'
  - file_name: 'perl-macros-5.16.3-286.el7.x86_64.rpm'
    url: 'https://buildlogs.centos.org/c7.1511.00/perl/20151120031510/5.16.3-286.el7.x86_64/perl-macros-5.16.3-286.el7.x86_64.rpm'
  - file_name: 'perl-parent-0.225-244.el7.noarch.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-parent-0.225-244.el7.noarch.rpm'
  - file_name: 'perl-PathTools-3.40-5.el7.x86_64.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-PathTools-3.40-5.el7.x86_64.rpm'
  - file_name: 'perl-Pod-Escapes-1.04-286.el7.noarch.rpm'
    url: 'https://buildlogs.centos.org/c7.1511.00/perl/20151120031510/5.16.3-286.el7.x86_64/perl-Pod-Escapes-1.04-286.el7.noarch.rpm'
  - file_name: 'perl-Pod-Perldoc-3.20-4.el7.noarch.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Pod-Perldoc-3.20-4.el7.noarch.rpm'
  - file_name: 'perl-Pod-Simple-3.28-4.el7.noarch.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Pod-Simple-3.28-4.el7.noarch.rpm'
  - file_name: 'perl-Pod-Usage-1.63-3.el7.noarch.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Pod-Usage-1.63-3.el7.noarch.rpm'
  - file_name: 'perl-podlators-2.5.1-3.el7.noarch.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-podlators-2.5.1-3.el7.noarch.rpm'
  - file_name: 'perl-Scalar-List-Utils-1.27-248.el7.x86_64.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Scalar-List-Utils-1.27-248.el7.x86_64.rpm'
  - file_name: 'perl-Socket-2.010-3.el7.x86_64.rpm'
    url: 'http://events.gauchocast.ucsb.edu/upgrade/Packages/perl-Socket-2.010-3.el7.x86_64.rpm'
  - file_name: 'perl-Storable-2.45-3.el7.x86_64.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Storable-2.45-3.el7.x86_64.rpm'
  - file_name: 'perl-Text-ParseWords-3.29-4.el7.noarch.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Text-ParseWords-3.29-4.el7.noarch.rpm'
  - file_name: 'perl-threads-1.87-4.el7.x86_64.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-threads-1.87-4.el7.x86_64.rpm'
  - file_name: 'perl-threads-shared-1.43-6.el7.x86_64.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-threads-shared-1.43-6.el7.x86_64.rpm'
  - file_name: 'perl-Time-HiRes-1.9725-3.el7.x86_64.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Time-HiRes-1.9725-3.el7.x86_64.rpm'
  - file_name: 'perl-Time-Local-1.2300-2.el7.noarch.rpm'
    url: 'http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Time-Local-1.2300-2.el7.noarch.rpm'
