rpm_path: /root/setup/ec_main
install_flag: true
download_flag: true
db_address: 192.168.0.182
db_name: msf_ec_1
controller_cidr: 192.168.0.0/24
ha_flag: false
act_address: none
act_node_name: none
sby_address: none
sby_node_name: none
cluster_name: none
