ec_path: /usr/ec_main
download_flag: false
log_path: logs/ec/log
installing_ec_path: /root/setup/ec_main
ec_jar_name: EcMainModule.jar
db_address: 192.168.0.183
db_name: msf_ec
ec_physical_address: 192.168.0.184
ec_listening_address: 192.168.0.188
ec_rest_port: 18080
em_netconf_address: 192.168.0.189
em_rest_port: 8080
em_rest_address: 192.168.0.189
em_netconf_port: 830
fc_rest_address: 192.168.0.125
fc_rest_port: 18078
dhcp_if_name: eth0
device_cidr: 192.168.53.1/16
controller_cidr: 192.168.0.0/24
ntp_server_address: 192.168.0.64
ha_flag: true
act_address: 172.16.0.184
act_node_name: ec-0
sby_address: 172.16.0.185
sby_node_name: ec-1
cluster_name: ec_cluster
oppo_login_address: 192.168.0.185
oppo_usrname: root
oppo_password: admin123
